"""Generate the pure A4 9x6 checkerboard documented by OpenCV."""

from __future__ import annotations

import argparse
from pathlib import Path

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.pdfgen.canvas import Canvas


def build(output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    page_width, page_height = landscape(A4)
    square = 25 * mm
    columns, rows = 10, 7  # 9x6 inner corners
    board_width = columns * square
    board_height = rows * square
    origin_x = (page_width - board_width) / 2
    origin_y = (page_height - board_height) / 2

    canvas = Canvas(str(output), pagesize=landscape(A4), pageCompression=1)
    canvas.setTitle("OpenCV 9x6 A4 calibration checkerboard")
    canvas.setAuthor("OpenCV-compatible pattern generated by RPI360")
    canvas.setFillColorRGB(1, 1, 1)
    canvas.rect(0, 0, page_width, page_height, fill=1, stroke=0)

    canvas.setFillColorRGB(0, 0, 0)
    for row in range(rows):
        for column in range(columns):
            if (row + column) % 2 == 0:
                canvas.rect(
                    origin_x + column * square,
                    origin_y + row * square,
                    square,
                    square,
                    fill=1,
                    stroke=0,
                )
    canvas.showPage()
    canvas.save()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output",
        type=Path,
        nargs="?",
        default=Path("hardware/calibration/checkerboard-9x6-a4.pdf"),
    )
    args = parser.parse_args()
    build(args.output)
    print(args.output)


if __name__ == "__main__":
    main()
